tabWidth: 2
# useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
# rangeStart: 0
# rangeEnd: Infinity
# parser: Prettier automatically infers the parser from the input file path, so you shouldn’t have to change this setting.
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
#
# overrides:
#   - files: '*.html'
#     options:
#       tabWidth: 2
